# Generated by Django 2.1.3 on 2018-11-03 16:58

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = []

    operations = [
        migrations.CreateModel(
            name="TgUser",
            fields=[
                ("code", models.CharField(max_length=8)),
                ("username", models.CharField(max_length=50, unique=True)),
                (
                    "telegram_id",
                    models.IntegerField(primary_key=True, serialize=False, unique=True),
                ),
            ],
        ),
    ]
